// <auto-generated />
using System;
using ClothingStoreWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClothingStoreWebAPI.Migrations
{
    [DbContext(typeof(ClothingStoreContext))]
    partial class ClothingStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClothingStoreWebAPI.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Homme"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Femme"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Enfant"
                        });
                });

            modelBuilder.Entity("ClothingStoreWebAPI.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            OrderDate = new DateOnly(2024, 3, 4),
                            Status = "Validée",
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 2,
                            OrderDate = new DateOnly(2024, 3, 1),
                            Status = "En attente",
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 3,
                            OrderDate = new DateOnly(2024, 2, 29),
                            Status = "Expédiée",
                            UserId = 2
                        },
                        new
                        {
                            OrderId = 4,
                            OrderDate = new DateOnly(2024, 2, 14),
                            Status = "Livrée",
                            UserId = 2
                        },
                        new
                        {
                            OrderId = 5,
                            OrderDate = new DateOnly(2023, 12, 15),
                            Status = "Livrée",
                            UserId = 3
                        },
                        new
                        {
                            OrderId = 6,
                            OrderDate = new DateOnly(2023, 12, 18),
                            Status = "Livrée",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("ClothingStoreWebAPI.Entities.OrderProduct", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ProductId = 1,
                            Price = 49.75,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 1,
                            ProductId = 3,
                            Price = 9.9900000000000002,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = 1,
                            Price = 59.990000000000002,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = 2,
                            Price = 19.989999999999998,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = 3,
                            Price = 12.99,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("ClothingStoreWebAPI.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Brand = "Charles Tyrwhitt",
                            CategoryId = 1,
                            Color = "Bleu ciel",
                            Description = "Fabriqué en pur coton doux et respirant.",
                            ImageURL = "https://www.charlestyrwhitt.com/on/demandware.static/-/Sites-ctshirts-master/default/dwebe4f658/hi-res/FON0409SKY_COLLAR_DETAIL.jpg",
                            Name = "Chemise col classique homme",
                            Price = 49.75,
                            QuantityInStock = 1000,
                            Size = "S"
                        },
                        new
                        {
                            ProductId = 2,
                            Brand = "Liberto",
                            CategoryId = 2,
                            Color = "Noir",
                            Description = "Robe élégante pour les occasions spéciales.",
                            ImageURL = "https://www.lahalle.com/dw/image/v2/BCHM_PRD/on/demandware.static/-/Sites-lahalle_master/default/dwbeb2b943/robe-de-soiree-droite-manches-longues-noir-femme-vue1-36165600645731061.jpg?sw=1600&sh=1600",
                            Name = "Robe de soirée",
                            Price = 19.989999999999998,
                            QuantityInStock = 500,
                            Size = "M"
                        },
                        new
                        {
                            ProductId = 3,
                            Brand = "Mango Kids",
                            CategoryId = 3,
                            Color = "Bleu foncé",
                            Description = "Jean slim pour un look décontracté.",
                            ImageURL = "https://img01.ztat.net/article/spp-media-p1/84a52eefe191416d8831bbfd7d951685/158458b6cba74cd59725f434bc297b78.jpg?imwidth=1800&filter=packshot",
                            Name = "Jean slim garçon",
                            Price = 9.9900000000000002,
                            QuantityInStock = 700,
                            Size = "10 ans"
                        },
                        new
                        {
                            ProductId = 5,
                            Brand = "Tezenis",
                            CategoryId = 3,
                            Color = "Bleu ciel/Gris",
                            Description = "60% coton, 40% polyester",
                            ImageURL = "https://img01.ztat.net/article/spp-media-p1/e9f7714483f24ce6bf4e7ea017e64fc2/16c300d2b8434a0cbf89e5b6dbc69451.jpg?imwidth=156&filter=packshot",
                            Name = "Pyjama Cartoon",
                            Price = 25.629999999999999,
                            QuantityInStock = 263,
                            Size = "S"
                        },
                        new
                        {
                            ProductId = 6,
                            Brand = "Pinko",
                            CategoryId = 2,
                            Color = "Vert",
                            Description = "Robe longue inspiration Asiatique",
                            ImageURL = "https://img01.ztat.net/article/spp-media-p1/f64de54bbdcc4bb1a4e606378a5fcaae/b62ca0fc6cad4713974bf01fb89cd45c.jpg?imwidth=156&filter=packshot",
                            Name = "SUSHI ABITO - Robe longue",
                            Price = 394.94999999999999,
                            QuantityInStock = 6,
                            Size = "M"
                        },
                        new
                        {
                            ProductId = 7,
                            Brand = "ONLY",
                            CategoryId = 2,
                            Color = "Vert",
                            Description = "Composition: 60% coton, 40% polyester\r\nMatière: Sweat",
                            ImageURL = "https://img01.ztat.net/article/spp-media-p1/3bea6fcc60564c99a2f46a38c97432df/bb8d59aa88f54942ac1ec10c72cc276a.jpg?imwidth=156&filter=packshot",
                            Name = "ONLBROOKE O NECK FLOWER - Sweatshirt",
                            Price = 32.990000000000002,
                            QuantityInStock = 48,
                            Size = "S"
                        },
                        new
                        {
                            ProductId = 8,
                            Brand = "LEVI",
                            CategoryId = 1,
                            Color = "Noir",
                            Description = "Composition: 98% coton, 2% élasthanne",
                            ImageURL = "https://img01.ztat.net/article/spp-media-p1/04a16d77bfc94d65aba8294306692a3b/302bec109d6842bf9de5c16039692710.jpg?imwidth=156",
                            Name = "Pantalon cargo",
                            Price = 48.990000000000002,
                            QuantityInStock = 855,
                            Size = "L"
                        },
                        new
                        {
                            ProductId = 9,
                            Brand = "Jack & Jones",
                            CategoryId = 1,
                            Color = "Blanc",
                            Description = "Composition: 100% coton",
                            ImageURL = "https://img01.ztat.net/article/spp-media-p1/30a2e37ae97d4a499d9178d558151f79/4031697abb324a7ebc982fc69b227842.jpg?imwidth=156&filter=packshot",
                            Name = "JORCALIFLO TEE CREW NECK - T-shirt imprimé",
                            Price = 95.349999999999994,
                            QuantityInStock = 632,
                            Size = "S"
                        });
                });

            modelBuilder.Entity("ClothingStoreWebAPI.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("BillingAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DeliveryAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BillingAdress = "Grenoble, France",
                            DateOfBirth = new DateOnly(1999, 1, 1),
                            DeliveryAdress = "Grenoble, France",
                            Email = "mouhammad.nour@gmail.com",
                            FirstName = "Mouhammad",
                            IsAdmin = true,
                            LastName = "Nour",
                            Password = "MouhammadN_1",
                            PhoneNumber = "0606060601"
                        },
                        new
                        {
                            UserId = 2,
                            BillingAdress = "Clermont-Ferrand, France",
                            DateOfBirth = new DateOnly(2000, 1, 1),
                            DeliveryAdress = "Clermont-Ferrand, France",
                            Email = "hasanbasri.caglayan@gmail.com",
                            FirstName = "Hasan-Basri",
                            IsAdmin = true,
                            LastName = "Caglayan",
                            Password = "HasanBasriC_2",
                            PhoneNumber = "0606060602"
                        },
                        new
                        {
                            UserId = 3,
                            BillingAdress = "Paris, France",
                            DateOfBirth = new DateOnly(2001, 1, 1),
                            DeliveryAdress = "Paris, France",
                            Email = "victor.hugo@gmail.com",
                            FirstName = "Victor",
                            IsAdmin = false,
                            LastName = "Hugo",
                            Password = "VictorH_3",
                            PhoneNumber = "0606060603"
                        },
                        new
                        {
                            UserId = 4,
                            BillingAdress = "Marseille, France",
                            DateOfBirth = new DateOnly(2002, 1, 1),
                            DeliveryAdress = "Marseille, France",
                            Email = "albert.camus@gmail.com",
                            FirstName = "Albert",
                            IsAdmin = false,
                            LastName = "Camus",
                            Password = "AlbertC_4",
                            PhoneNumber = "0606060604"
                        });
                });

            modelBuilder.Entity("ClothingStoreWebAPI.Entities.Order", b =>
                {
                    b.HasOne("ClothingStoreWebAPI.Entities.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClothingStoreWebAPI.Entities.OrderProduct", b =>
                {
                    b.HasOne("ClothingStoreWebAPI.Entities.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStoreWebAPI.Entities.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ClothingStoreWebAPI.Entities.Product", b =>
                {
                    b.HasOne("ClothingStoreWebAPI.Entities.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClothingStoreWebAPI.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ClothingStoreWebAPI.Entities.Order", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ClothingStoreWebAPI.Entities.Product", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ClothingStoreWebAPI.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
